orbs:
  node: circleci/node@4.1.0
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  build:
    docker:
      - image: circleci/node:12.0-browsers
    environment: 
      CHROME_BIN: /usr/bin/google-chrome
    steps:
      - checkout
      - run: npm install
      - run: npm test -- --no-watch
        
version: 2.1

workflows:
  app-tests:
    jobs:
      - build
