orbs:
  node: circleci/node@4.1.0
        
version: 2.1

workflows:
  app-tests:
    jobs:
      build:
        docker: 
          - image:  circleci/node:10
          environment:
              - CHROME_BIN=/usr/bin/google-chrome
        steps:
          - node/test