orbs:
  node: circleci/node@4.1.0
        
version: 2.1

jobs:
  build:
    docker: 
      - image:  circleci/node:10
       environment: CHROME_BIN=/usr/bin/google-chrome

workflows:
  app-tests:
    jobs:
      - build
      - node/test