orbs:
  browser-tools: circleci/browser-tools@1.1.0
  node: circleci/node@4.1.0
        
version: 2.1

jobs:
  test:
      docker:
        - image: 'cimg/node:13.12-browser'
      steps:
        - browser-tools/install-browser-tools

workflows:
  app-tests:
    jobs:
      - node/test